---

require:
- rubocop-minitest
- rubocop-rake

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/ConstantOverwrittenInRescue:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateMagicComment:
  Enabled: true

Lint/DuplicateMatchPattern:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/ItWithoutArgumentsInBlock:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/LiteralAssignmentInCondition:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedCaseRange:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NonAtomicFileOperation:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RedundantRegexpQuantifiers:
  Enabled: true

Lint/RefinementImportMethods:
  Enabled: true

Lint/RequireRangeParentheses:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessRescue:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Metrics/CollectionLiteralLength:
  Enabled: true

Minitest/AssertInDelta:
  Enabled: true

Minitest/AssertKindOf:
  Enabled: true

Minitest/AssertOperator:
  Enabled: true

Minitest/AssertOutput:
  Enabled: true

Minitest/AssertPathExists:
  Enabled: true

Minitest/AssertPredicate:
  Enabled: true

Minitest/AssertRaisesCompoundBody:
  Enabled: true

Minitest/AssertRaisesWithRegexpArgument:
  Enabled: true

Minitest/AssertSame:
  Enabled: true

Minitest/AssertSilent:
  Enabled: true

Minitest/AssertWithExpectedArgument:
  Enabled: true

Minitest/AssertionInLifecycleHook:
  Enabled: true

Minitest/DuplicateTestRun:
  Enabled: true

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: true

Minitest/LifecycleHooksOrder:
  Enabled: true

Minitest/LiteralAsActualArgument:
  Enabled: true

Minitest/MultipleAssertions:
  Enabled: true
  Max: 5

Minitest/NonExecutableTestMethod:
  Enabled: true

Minitest/NonPublicTestMethod:
  Enabled: true

Minitest/RedundantMessageArgument:
  Enabled: true

Minitest/RefuteInDelta:
  Enabled: true

Minitest/RefuteKindOf:
  Enabled: true

Minitest/RefuteOperator:
  Enabled: true

Minitest/RefutePathExists:
  Enabled: true

Minitest/RefutePredicate:
  Enabled: true

Minitest/RefuteSame:
  Enabled: true

Minitest/ReturnInTestMethod:
  Enabled: true

Minitest/SkipEnsure:
  Enabled: true

Minitest/SkipWithoutReason:
  Enabled: true

Minitest/TestFileName:
  Enabled: true

Minitest/TestMethodName:
  Enabled: true

Minitest/UnreachableAssertion:
  Enabled: true

Minitest/UnspecifiedException:
  Enabled: true

Minitest/UselessAssertion:
  Enabled: true

Naming/BlockForwarding:
  Enabled: true

Security/CompoundHash:
  Enabled: true

Security/IoMethods:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/ArrayIntersect:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/ComparableClamp:
  Enabled: true

Style/ConcatArrayLiterals:
  Enabled: true

Style/DataInheritance:
  Enabled: true

Style/DirEmpty:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EmptyHeredoc:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/EnvHome:
  Enabled: true

Style/ExactRegexpMatch:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FetchEnvVar:
  Enabled: true

Style/FileEmpty:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/MagicCommentFormat:
  Enabled: true

Style/MapCompactWithConditionalBlock:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MapToSet:
  Enabled: true

Style/MinMaxComparison:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NestedFileDirname:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/ObjectThen:
  Enabled: true

Style/OpenStructUse:
  Enabled: true

Style/OperatorMethodCall:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantArrayConstructor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantConstantBase:
  Enabled: true

Style/RedundantCurrentDirectoryInPath:
  Enabled: true

Style/RedundantDoubleSplatHashBraces:
  Enabled: true

Style/RedundantEach:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantFilterChain:
  Enabled: true

Style/RedundantHeredocDelimiterQuotes:
  Enabled: true

Style/RedundantInitialize:
  Enabled: true

Style/RedundantLineContinuation:
  Enabled: true

Style/RedundantRegexpArgument:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpConstructor:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SingleLineDoEndBlock:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SuperWithArgsParentheses:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/YAMLFileRead:
  Enabled: true

Style/YodaExpression:
  Enabled: true
