env:
  RUBY_VERSION: 2.7
  CC_TEST_REPORTER_BINARY_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

name: Continuous Integration
on: [push, pull_request]

jobs:
  test:
    name: Run bin/test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      # install gems
      - name: Cache Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # prepare CC test reporter
      - name: Download CC test reporter binary
        run: |
          curl -L ${CC_TEST_REPORTER_BINARY_URL} > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      # run tests
      - name: Run tests
        run: bin/test

      # report to CC
      - run: ./cc-test-reporter after-build --exit-code 1
        if: ${{ failure() }}

      - run: ./cc-test-reporter after-build --exit-code 0
        if: ${{ success() }}
